query GetRecommendedRecipes {
  recipes(
    where: {
      likes_aggregate: { count: { predicate: { _gte: 2 } } }
      ratings_aggregate: { count: { predicate: { _gte: 5 } } }
    }
  ) {
    id
    title
    description
    preparation_time_minutes
    price_etb
    category {
      id
      name
    }
    ingredients {
      id
      name
    }
    recipe_images(where: { is_featured: { _eq: true } }) {
      image_url
      is_featured
    }
    user {
      id
      first_name
      last_name
    }
    ratings_aggregate {
      aggregate {
        avg {
          rating
        }
        count
      }
    }
  }
}
